    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Update Latest Image
      run: |
        LATEST_IMG=$(ls -Art image_*.jpg | tail -n 1)
        cp $LATEST_IMG image_latest.jpg
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add image_latest.jpg
        git commit -m "Update latest image"
        git push --set-upstream https://${{ secrets.ACCESS_TOKEN }}@github.com/yuk1-kondo/owa-sensor.git main
